### ISSUE TITLE
feat: less configuration(default css, template)

### ISSUE THREAD

**Issue by dongsik-yoo** [nhnent/tui.calendar#76]
## Version

v1.0.2

## Development Environment

Chrome
Mac

## Current Behavior

There are some configurations which can be removed for beginners.
For example
```css
#calendar {
  position: relative;
}

#calendar * {
  box-sizing: border-box;
}
```

## Expected Behavior

Supports default css and templates to make it ease usage
